
/* menuseg.c */
void CloseCaptureFile(short w);
void AdjustMenus(void);
void switchMenus(short, short);
void setupmenu(short, DialogPtr);
void CheckOpSpecSubmenu(void);
void SetupOpSpecSubmenu(MenuHandle theMenu);
void updateMenuChecks(void);
void DisplayMacBinary(void);
void CheckFonts(void);
void applAbout(void);
short ReallyClose(short scrn);
PicHandle RGtoPICT(short i);
void copyGraph(short dnum);
void copyText(short vs);
void copyTable(short vs);
void paste(void);
void autoPaste(short vs);
void displayStatus(short n);
void changeport(short oldprt, short newprt);
Boolean	HandleQuit(void);
void HandleMenuCommand(long mResult, short modifiers);
void	CheckNational(short choice);
short portsOpen(void);
void extractmenu(short screen);
void addinmenu(short screen, Str255 temps, char mark);
void SetMenuMarkToOpeningForAGivenScreen(short scrn);
void SetMenuMarkToLiveForAGivenScreen(short scrn);
void DoTheMenuChecks(void);
void SetMenusForSelection(short selected);
void SetScreenDimensions(short, short);
void	ChangeWindowName(WindowPtr	theWindow);
void	set_new_window_name(Str255 theName, WindowPtr theWindow);
long SetOtherFontSize(short currentSize);
void switchToOptionMenus(Boolean useOptionedStuff);
void addMonoSpacedFonts(MenuHandle, DialogPtr);
void scriptKbdInit(void);
void CheckDefaultScriptSettings(void);
Boolean isMonospacedFont(Str255 theFont);
void switchToShiftMenus(Boolean useShiftStuff);
void OpenSpecial(short);
void SaveSelectionToFile(void);
void SaveThisSelection(short);
void uploadFile(void);
