/* ANSI-C code produced by gperf version 2.7 */
/* Command-line: gperf -LANSI-C -t -c -C -l -k1,3,6,10,$ -N gperf_atom  */
/* Automatically generated by process_atoms,
 *  Thu Feb 1 09:10:23 CET 2001
 * Do not edit! */

struct atom_assoc { const char *name; int id; };

#define TOTAL_KEYWORDS 101
#define MIN_WORD_LENGTH 1
#define MAX_WORD_LENGTH 29
#define MIN_HASH_VALUE 1
#define MAX_HASH_VALUE 420
/* maximum key range = 420, duplicates = 0 */

#ifdef __GNUC__
__inline
#endif
static unsigned int
hash (register const char *str, register unsigned int len)
{
  static const unsigned short asso_values[] =
    {
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421,   5, 421, 421,   0, 421, 421,   5,  25,
       20,  15, 421,  20,  75, 421,  50,   0, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421,  15, 421,
      421, 421, 421, 421, 421, 421, 421,  40,  56, 120,
       60, 107,  10,  90,   0,  65,   0,  15,  10,   5,
       70,   5,  45,  25,  75,   0,   0,  15,   0,   5,
       35,  20,  40, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421, 421, 421, 421, 421,
      421, 421, 421, 421, 421, 421
    };
  register int hval = len;

  switch (hval)
    {
      default:
      case 10:
        hval += asso_values[(unsigned char)str[9]];
      case 9:
      case 8:
      case 7:
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      case 5:
      case 4:
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

#ifdef __GNUC__
__inline
#endif
const struct atom_assoc *
gperf_atom (register const char *str, register unsigned int len)
{
  static const unsigned char lengthtable[] =
    {
       0,  1,  0,  3,  4,  0,  0,  7,  0,  0,  0,  1,  0,  0,
       4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,
      13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
       0,  0,  0,  0,  0,  7,  3,  0,  0,  1,  0,  0,  0, 15,
       0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  2, 13,  4,
       9,  1,  0,  8,  9,  0,  0,  0,  8,  0,  0,  1,  7,  0,
      19,  0,  0,  0,  3,  0, 10,  1,  0,  0,  0,  0,  0,  0,
       0,  9,  0,  0,  0,  0,  4,  0,  0,  0,  0,  9,  3,  0,
       0,  1,  0,  0,  6,  0,  8, 14,  0,  1,  5, 13,  0,  0,
       0, 12,  8,  0,  0, 11,  5,  0,  0,  0,  0,  0,  0,  0,
       0,  1,  0,  3,  0,  0, 29,  0,  0,  0,  0,  1,  0,  0,
       0,  0,  0,  7,  0, 14, 15,  0,  0, 13,  0,  4,  0,  0,
       0, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
      10,  3,  0,  0,  4,  0,  0, 14,  0,  0, 11,  0,  0,  0,
       0,  0, 11,  7, 15,  0,  0,  0,  7,  0,  9,  0,  0, 14,
       8,  0,  0,  0, 14,  1,  0,  0,  0,  0, 15,  0,  0,  0,
       0,  0,  0, 12,  6,  0,  0,  0,  0, 11,  0, 18,  0, 12,
      26,  0, 13,  1,  0,  0,  0,  0, 29,  0, 11,  0,  9,  4,
       0,  0,  0,  0,  9,  7,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  0,  0,  0,  0, 14,  0,  0,  0,  0, 12,  0,  0,  0,
       0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       0, 11,  0, 20,  0, 11,  0, 14,  0,  0,  0,  0, 26,  0,
       0,  0,  4,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  0,  0,  0, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       0, 10,  0,  0,  0, 27,  8,  0,  0,  0,  0,  0,  0,  0,
      12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       8
    };
  static const struct atom_assoc wordlist[] =
    {
      {""},
      {"s", ATOM_S},
      {""},
      {"set", ATOM_SET},
      {"hash", ATOM_HASH},
      {""}, {""},
      {"ssh-dss", ATOM_SSH_DSS},
      {""}, {""}, {""},
      {"*", ATOM_STAR},
      {""}, {""},
      {"salt", ATOM_SALT},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""},
      {"ssh-userauth", ATOM_SSH_USERAUTH},
      {"spki-sign-dss", ATOM_SPKI_SIGN_DSS},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""},
      {"y", ATOM_Y},
      {""}, {""}, {""}, {""}, {""},
      {"ssh-rsa", ATOM_SSH_RSA},
      {"md5", ATOM_MD5},
      {""}, {""},
      {"q", ATOM_Q},
      {""}, {""}, {""},
      {"auth-ssh1-agent", ATOM_AUTH_SSH1_AGENT},
      {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {"acl", ATOM_ACL},
      {""}, {""}, {""},
      {"iv", ATOM_IV},
      {"spki-sign-rsa", ATOM_SPKI_SIGN_RSA},
      {"sha1", ATOM_SHA1},
      {"subsystem", ATOM_SUBSYSTEM},
      {"x", ATOM_X},
      {""},
      {"hmac-md5", ATOM_HMAC_MD5},
      {"hmac-sha1", ATOM_HMAC_SHA1},
      {""}, {""}, {""},
      {"Xpkcs5v2", ATOM_XPKCS5V2},
      {""}, {""},
      {"a", ATOM_A},
      {"session", ATOM_SESSION},
      {""},
      {"auth-ssh1-agent-req", ATOM_AUTH_SSH1_AGENT_REQ},
      {""}, {""}, {""},
      {"x11", ATOM_X11},
      {""},
      {"auth-agent", ATOM_AUTH_AGENT},
      {"p", ATOM_P},
      {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {"ssh-ring1", ATOM_SSH_RING1},
      {""}, {""}, {""}, {""},
      {"data", ATOM_DATA},
      {""}, {""}, {""}, {""},
      {"hostbased", ATOM_HOSTBASED},
      {"env", ATOM_ENV},
      {""}, {""},
      {"b", ATOM_B},
      {""}, {""},
      {"signal", ATOM_SIGNAL},
      {""},
      {"password", ATOM_PASSWORD},
      {"auth-agent-req", ATOM_AUTH_AGENT_REQ},
      {""},
      {"d", ATOM_D},
      {"shell", ATOM_SHELL},
      {"tcpip-forward", ATOM_TCPIP_FORWARD},
      {""}, {""}, {""},
      {"hmac-sha1-96", ATOM_HMAC_SHA1_96},
      {"xon-xoff", ATOM_XON_XOFF},
      {""}, {""},
      {"hmac-md5-96", ATOM_HMAC_MD5_96},
      {"entry", ATOM_ENTRY},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {"n", ATOM_N},
      {""},
      {"dsa", ATOM_DSA},
      {""}, {""},
      {"ssh-dss-kludge@lysator.liu.se", ATOM_SSH_DSS_KLUDGE_LOCAL},
      {""}, {""}, {""}, {""},
      {"r", ATOM_R},
      {""}, {""}, {""}, {""}, {""},
      {"version", ATOM_VERSION},
      {""},
      {"twofish192-cbc", ATOM_TWOFISH192_CBC},
      {"x509v3-sign-dss", ATOM_X509V3_SIGN_DSS},
      {""}, {""},
      {"rsa-pkcs1-md5", ATOM_RSA_PKCS1_MD5},
      {""},
      {"zlib", ATOM_ZLIB},
      {""}, {""}, {""},
      {"rsa-pkcs1-sha1", ATOM_RSA_PKCS1_SHA1},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""},
      {"g", ATOM_G},
      {"iterations", ATOM_ITERATIONS},
      {"tag", ATOM_TAG},
      {""}, {""},
      {"name", ATOM_NAME},
      {""}, {""},
      {"twofish128-cbc", ATOM_TWOFISH128_CBC},
      {""}, {""},
      {"twofish-cbc", ATOM_TWOFISH_CBC},
      {""}, {""}, {""}, {""}, {""},
      {"exit-status", ATOM_EXIT_STATUS},
      {"x11-req", ATOM_X11_REQ},
      {"x509v3-sign-rsa", ATOM_X509V3_SIGN_RSA},
      {""}, {""}, {""},
      {"pty-req", ATOM_PTY_REQ},
      {""},
      {"signature", ATOM_SIGNATURE},
      {""}, {""},
      {"ssh-connection", ATOM_SSH_CONNECTION},
      {"sequence", ATOM_SEQUENCE},
      {""}, {""}, {""},
      {"twofish256-cbc", ATOM_TWOFISH256_CBC},
      {"e", ATOM_E},
      {""}, {""}, {""}, {""},
      {"forwarded-tcpip", ATOM_FORWARDED_TCPIP},
      {""}, {""}, {""}, {""}, {""}, {""},
      {"pgp-sign-dss", ATOM_PGP_SIGN_DSS},
      {"prefix", ATOM_PREFIX},
      {""}, {""}, {""}, {""},
      {"exit-signal", ATOM_EXIT_SIGNAL},
      {""},
      {"password-encrypted", ATOM_PASSWORD_ENCRYPTED},
      {""},
      {"direct-tcpip", ATOM_DIRECT_TCPIP},
      {"diffie-hellman-group1-sha1", ATOM_DIFFIE_HELLMAN_GROUP1_SHA1},
      {""},
      {"window-change", ATOM_WINDOW_CHANGE},
      {"c", ATOM_C},
      {""}, {""}, {""}, {""},
      {"srp-ring1-sha1@lysator.liu.se", ATOM_SRP_RING1_SHA1_LOCAL},
      {""},
      {"private-key", ATOM_PRIVATE_KEY},
      {""},
      {"publickey", ATOM_PUBLICKEY},
      {"none", ATOM_NONE},
      {""}, {""}, {""}, {""},
      {"propagate", ATOM_PROPAGATE},
      {"arcfour", ATOM_ARCFOUR},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""},
      {"public-key", ATOM_PUBLIC_KEY},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""},
      {"pgp-sign-rsa", ATOM_PGP_SIGN_RSA},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {"serpent192-cbc", ATOM_SERPENT192_CBC},
      {""}, {""}, {""}, {""},
      {"srp-verifier", ATOM_SRP_VERIFIER},
      {""}, {""}, {""}, {""}, {""},
      {"aes192-cbc", ATOM_AES192_CBC},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""},
      {"certificate", ATOM_CERTIFICATE},
      {""},
      {"cancel-tcpip-forward", ATOM_CANCEL_TCPIP_FORWARD},
      {""},
      {"cast128-cbc", ATOM_CAST128_CBC},
      {""},
      {"serpent128-cbc", ATOM_SERPENT128_CBC},
      {""}, {""}, {""}, {""},
      {"serpent-cbc@lysator.liu.se", ATOM_SERPENT_CBC_LOCAL},
      {""}, {""}, {""},
      {"exec", ATOM_EXEC},
      {""},
      {"aes128-cbc", ATOM_AES128_CBC},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""},
      {"serpent256-cbc", ATOM_SERPENT256_CBC},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""},
      {"aes256-cbc", ATOM_AES256_CBC},
      {""}, {""}, {""},
      {"rijndael-cbc@lysator.liu.se", ATOM_RIJNDAEL_CBC_LOCAL},
      {"3des-cbc", ATOM_3DES_CBC},
      {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {"blowfish-cbc", ATOM_BLOWFISH_CBC},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""},
      {"idea-cbc", ATOM_IDEA_CBC}
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = wordlist[key].name;

            if (*str == *s && !strncmp (str + 1, s + 1, len - 1))
              return &wordlist[key];
          }
    }
  return 0;
}
