/* ANSI-C code produced by gperf version 2.7 */
/* Command-line: gperf -LANSI-C -t -c -C -l -k1,3,6,10,$ -N gperf_atom  */
/* Automatically generated by process_atoms,
 *  Sat Mar 17 21:49:57 CET 2001
 * Do not edit! */

struct atom_assoc { const char *name; int id; };

#define TOTAL_KEYWORDS 115
#define MIN_WORD_LENGTH 1
#define MAX_WORD_LENGTH 29
#define MIN_HASH_VALUE 1
#define MAX_HASH_VALUE 488
/* maximum key range = 488, duplicates = 0 */

#ifdef __GNUC__
__inline
#endif
static unsigned int
hash (register const char *str, register unsigned int len)
{
  static const unsigned short asso_values[] =
    {
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489,   5, 489, 489,   0, 489, 489,   0,  30,
       45,  20, 489,  10,  50, 489,  20,   0, 489, 489,
      489, 489, 489, 489, 489,  12, 489, 489, 489,  35,
        5,  55,  40,  35, 489,  50,   5,  10, 489, 489,
        0,  15,   0,   0,   0,  60,   0, 489,   5, 489,
      489, 489, 489, 489, 489, 489, 489,  40,  85, 108,
       90, 125,  50,  60,   0,  65,   0, 125,   5,  35,
       65,  10,  75,  25,  45,   0,   0,  25,   0,  10,
       80, 105,  35, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489, 489, 489, 489, 489,
      489, 489, 489, 489, 489, 489
    };
  register int hval = len;

  switch (hval)
    {
      default:
      case 10:
        hval += asso_values[(unsigned char)str[9]];
      case 9:
      case 8:
      case 7:
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      case 5:
      case 4:
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

#ifdef __GNUC__
__inline
#endif
const struct atom_assoc *
gperf_atom (register const char *str, register unsigned int len)
{
  static const unsigned char lengthtable[] =
    {
       0,  1,  0,  3,  4,  0,  0,  7,  0,  4,  0,  1,  0,  0,
       4,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,
       0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  3,  4,  0,  0,
       0,  3,  0,  0,  0,  7,  3,  0,  0,  1,  0,  3,  4, 15,
       0,  0,  3,  4,  0,  0,  0,  0,  4,  0,  0,  2,  0,  0,
       0,  0,  0,  0,  4,  0,  6,  0,  3,  9,  0,  1,  7,  0,
      19,  0,  0,  0,  0,  0, 10,  1,  0,  8,  4,  0,  0,  0,
       0,  0,  0,  0, 12,  0,  9,  0,  0,  0,  0,  4,  0,  0,
       0,  0,  0,  0,  0,  0,  0, 14,  0,  1,  0,  3,  0,  0,
       0,  7,  3,  9,  0,  1,  0,  0,  4,  5, 11,  0, 13,  9,
       0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  1, 14,  0,
       0,  0,  0,  0,  0, 29,  0,  1,  0,  0,  0,  0,  0,  0,
       0,  0,  0,  1,  0,  3,  0, 15,  0, 14, 13,  0,  0,  1,
      14,  8,  0,  0,  0,  0, 13,  4,  0,  0,  0,  8,  9,  0,
       0, 14,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  1,  0,  8, 11, 15,  0,  1,  0,  0,  0,  0,  0,  8,
       0,  7, 11,  0,  0,  4, 15,  0,  0, 13,  0,  5,  0,  0,
       0,  0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0,  1,
      14,  0, 14,  0,  0,  0,  0,  4,  0,  0,  0, 13,  0,  0,
       0,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0, 14,  0,  9,
       0,  0, 14,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,
      29,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  0,  0, 10, 12,  0,  0,  0, 10, 12, 18,  0,  0,  0,
      12,  0,  0,  0, 26,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  7,  0, 11,  0,  0,  0,  0, 29, 27, 26,  0,  0,  0,
       0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0,  4, 20,
       0,  0,  6,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  0,  0, 11,  9,  0,  0,  0,  0,  0, 12,  0,  0,  0,
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10
    };
  static const struct atom_assoc wordlist[] =
    {
      {""},
      {"s", ATOM_S},
      {""},
      {"set", ATOM_SET},
      {"hash", ATOM_HASH},
      {""}, {""},
      {"ssh-dss", ATOM_SSH_DSS},
      {""},
      {"salt", ATOM_SALT},
      {""},
      {"*", ATOM_STAR},
      {""}, {""},
      {"TERM", ATOM_TERM},
      {""},
      {"ABRT", ATOM_ABRT},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {"ALRM", ATOM_ALRM},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""},
      {"ssh-userauth", ATOM_SSH_USERAUTH},
      {"INT", ATOM_INT},
      {"PIPE", ATOM_PIPE},
      {""}, {""}, {""},
      {"HUP", ATOM_HUP},
      {""}, {""}, {""},
      {"ssh-rsa", ATOM_SSH_RSA},
      {"ILL", ATOM_ILL},
      {""}, {""},
      {"q", ATOM_Q},
      {""},
      {"acl", ATOM_ACL},
      {"QUIT", ATOM_QUIT},
      {"auth-ssh1-agent", ATOM_AUTH_SSH1_AGENT},
      {""}, {""},
      {"md5", ATOM_MD5},
      {"SEGV", ATOM_SEGV},
      {""}, {""}, {""}, {""},
      {"KILL", ATOM_KILL},
      {""}, {""},
      {"iv", ATOM_IV},
      {""}, {""}, {""}, {""}, {""}, {""},
      {"sha1", ATOM_SHA1},
      {""},
      {"signal", ATOM_SIGNAL},
      {""},
      {"FPE", ATOM_FPE},
      {"hmac-sha1", ATOM_HMAC_SHA1},
      {""},
      {"a", ATOM_A},
      {"session", ATOM_SESSION},
      {""},
      {"auth-ssh1-agent-req", ATOM_AUTH_SSH1_AGENT_REQ},
      {""}, {""}, {""}, {""}, {""},
      {"auth-agent", ATOM_AUTH_AGENT},
      {"r", ATOM_R},
      {""},
      {"hmac-md5", ATOM_HMAC_MD5},
      {"USR1", ATOM_USR1},
      {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {"hmac-sha1-96", ATOM_HMAC_SHA1_96},
      {""},
      {"ssh-ring1", ATOM_SSH_RING1},
      {""}, {""}, {""}, {""},
      {"USR2", ATOM_USR2},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {"auth-agent-req", ATOM_AUTH_AGENT_REQ},
      {""},
      {"g", ATOM_G},
      {""},
      {"tag", ATOM_TAG},
      {""}, {""}, {""},
      {"version", ATOM_VERSION},
      {"env", ATOM_ENV},
      {"subsystem", ATOM_SUBSYSTEM},
      {""},
      {"n", ATOM_N},
      {""}, {""},
      {"data", ATOM_DATA},
      {"shell", ATOM_SHELL},
      {"hmac-md5-96", ATOM_HMAC_MD5_96},
      {""},
      {"spki-sign-dss", ATOM_SPKI_SIGN_DSS},
      {"hostbased", ATOM_HOSTBASED},
      {""}, {""}, {""},
      {"x11", ATOM_X11},
      {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {"p", ATOM_P},
      {"twofish128-cbc", ATOM_TWOFISH128_CBC},
      {""}, {""}, {""}, {""}, {""}, {""},
      {"ssh-dss-kludge@lysator.liu.se", ATOM_SSH_DSS_KLUDGE_LOCAL},
      {""},
      {"x", ATOM_X},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {"b", ATOM_B},
      {""},
      {"dsa", ATOM_DSA},
      {""},
      {"x509v3-sign-dss", ATOM_X509V3_SIGN_DSS},
      {""},
      {"twofish192-cbc", ATOM_TWOFISH192_CBC},
      {"spki-sign-rsa", ATOM_SPKI_SIGN_RSA},
      {""}, {""},
      {"d", ATOM_D},
      {"twofish256-cbc", ATOM_TWOFISH256_CBC},
      {"password", ATOM_PASSWORD},
      {""}, {""}, {""}, {""},
      {"tcpip-forward", ATOM_TCPIP_FORWARD},
      {"zlib", ATOM_ZLIB},
      {""}, {""}, {""},
      {"Xpkcs5v2", ATOM_XPKCS5V2},
      {"signature", ATOM_SIGNATURE},
      {""}, {""},
      {"ssh-connection", ATOM_SSH_CONNECTION},
      {""}, {""},
      {"iterations", ATOM_ITERATIONS},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""},
      {"y", ATOM_Y},
      {""},
      {"xon-xoff", ATOM_XON_XOFF},
      {"twofish-cbc", ATOM_TWOFISH_CBC},
      {"x509v3-sign-rsa", ATOM_X509V3_SIGN_RSA},
      {""},
      {"c", ATOM_C},
      {""}, {""}, {""}, {""}, {""},
      {"sequence", ATOM_SEQUENCE},
      {""},
      {"arcfour", ATOM_ARCFOUR},
      {"exit-status", ATOM_EXIT_STATUS},
      {""}, {""},
      {"name", ATOM_NAME},
      {"forwarded-tcpip", ATOM_FORWARDED_TCPIP},
      {""}, {""},
      {"rsa-pkcs1-md5", ATOM_RSA_PKCS1_MD5},
      {""},
      {"entry", ATOM_ENTRY},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""},
      {"exit-signal", ATOM_EXIT_SIGNAL},
      {""}, {""}, {""}, {""},
      {"e", ATOM_E},
      {"serpent128-cbc", ATOM_SERPENT128_CBC},
      {""},
      {"rsa-pkcs1-sha1", ATOM_RSA_PKCS1_SHA1},
      {""}, {""}, {""}, {""},
      {"none", ATOM_NONE},
      {""}, {""}, {""},
      {"window-change", ATOM_WINDOW_CHANGE},
      {""}, {""}, {""},
      {"x11-req", ATOM_X11_REQ},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {"serpent192-cbc", ATOM_SERPENT192_CBC},
      {""},
      {"propagate", ATOM_PROPAGATE},
      {""}, {""},
      {"serpent256-cbc", ATOM_SERPENT256_CBC},
      {""}, {""}, {""},
      {"aes128-cbc", ATOM_AES128_CBC},
      {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {"srp-ring1-sha1@lysator.liu.se", ATOM_SRP_RING1_SHA1_LOCAL},
      {""}, {""},
      {"direct-tcpip", ATOM_DIRECT_TCPIP},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""},
      {"aes192-cbc", ATOM_AES192_CBC},
      {"pgp-sign-rsa", ATOM_PGP_SIGN_RSA},
      {""}, {""}, {""},
      {"aes256-cbc", ATOM_AES256_CBC},
      {"pgp-sign-dss", ATOM_PGP_SIGN_DSS},
      {"password-encrypted", ATOM_PASSWORD_ENCRYPTED},
      {""}, {""}, {""},
      {"srp-verifier", ATOM_SRP_VERIFIER},
      {""}, {""}, {""},
      {"diffie-hellman-group1-sha1", ATOM_DIFFIE_HELLMAN_GROUP1_SHA1},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""},
      {"pty-req", ATOM_PTY_REQ},
      {""},
      {"certificate", ATOM_CERTIFICATE},
      {""}, {""}, {""}, {""},
      {"signal-unknown@lysator.liu.se", ATOM_SIGNAL_UNKNOWN_LOCAL},
      {"rijndael-cbc@lysator.liu.se", ATOM_RIJNDAEL_CBC_LOCAL},
      {"serpent-cbc@lysator.liu.se", ATOM_SERPENT_CBC_LOCAL},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""},
      {"cast128-cbc", ATOM_CAST128_CBC},
      {""}, {""}, {""}, {""},
      {"exec", ATOM_EXEC},
      {"cancel-tcpip-forward", ATOM_CANCEL_TCPIP_FORWARD},
      {""}, {""},
      {"prefix", ATOM_PREFIX},
      {""}, {""},
      {"3des-cbc", ATOM_3DES_CBC},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""},
      {"private-key", ATOM_PRIVATE_KEY},
      {"publickey", ATOM_PUBLICKEY},
      {""}, {""}, {""}, {""}, {""},
      {"blowfish-cbc", ATOM_BLOWFISH_CBC},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {"idea-cbc", ATOM_IDEA_CBC},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""},
      {"public-key", ATOM_PUBLIC_KEY}
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        if (len == lengthtable[key])
          {
            register const char *s = wordlist[key].name;

            if (*str == *s && !strncmp (str + 1, s + 1, len - 1))
              return &wordlist[key];
          }
    }
  return 0;
}
