void	CONFIGUREunload(void);
void Cenviron( void);
void Cftp( void);
Boolean GetApplicationType(OSType *type);
void	BoundsCheck(long *value, long high, long low);
void EditConfigType(ResType ConfigResourceType, Boolean (*EditFunction)());
Boolean EditTerminal(StringPtr PrefRecordNamePtr);
Boolean EditSession(StringPtr PrefRecordNamePtr);
Boolean EditFTPUser(StringPtr PrefRecordNamePtr);
pascal short ColorBoxModalProc( DialogPtr dptr, EventRecord *evt, short *item);
PROTO_UPP(ColorBoxModalProc, ModalFilter);
pascal void	ColorBoxItemProc(DialogPtr theDlg, short itemNo);
PROTO_UPP(ColorBoxItemProc, UserItem);
void SetSessionData(DialogPtr, SessionPrefs*, char*, StringPtr);
short AnsiPrompt(short, short*);
void HideSessPanel(DialogPtr, short);
void ShowSessPanel(DialogPtr, short);
void HideTermPanel(DialogPtr, short);
void ShowTermPanel(DialogPtr, short);
void DeleteRange(char *buffer,short start,short end);
void InsertChar(char *buffer,short pos,char c);
OSErr GetScrapHandle( FlavorType dataFlavor, Handle *dataHandle );
Boolean PasswordFilter(DialogPtr dptr, EventRecord *evt, unsigned char *buf, short max);
