#! /bin/sh

# Tests connecting with lsh. In order to use this, you must already
# have lsh set up so that you can login without password.

# This restriction can be fixed if we add an option to lshd to use a
# custom passwd-file.

echo lshg, cat 2 test

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

spawn_lshd && spawn_lsh -G && sleep 20 && cat ../lshd | exec_lshg cat ">" "`pwd`/test.out1"
cat ../lshd > test.out2

compare_output "lshg-cat-2-test"


